<?php
// Start output buffering to prevent 'headers already sent' errors
ob_start();

// Start session if not already started
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// Ensure user is logged in and has a valid user_id
if (!isset($_SESSION['id']) || empty($_SESSION['id'])) {
    // Redirect to login if no user_id is set
    header("Location: login.php");
    exit;
}

// Assign user_id from session['id'] to be consistent with header.php
$_SESSION['user_id'] = $_SESSION['id'];

$page_title = "My Documents";
$page_specific_css = "assets/css/documents.css";
require_once 'includes/header.php';

// Get all document categories
$query = "SELECT * FROM document_categories ORDER BY name";
$stmt = $conn->prepare($query);
$stmt->execute();
$categories_result = $stmt->get_result();
$categories = [];

if ($categories_result && $categories_result->num_rows > 0) {
    while ($row = $categories_result->fetch_assoc()) {
        $categories[] = $row;
    }
}
$stmt->close();

// Get all document types
$query = "SELECT dt.*, dc.name as category_name 
          FROM document_types dt 
          JOIN document_categories dc ON dt.category_id = dc.id 
          WHERE dt.is_active = 1
          ORDER BY dt.name";
$stmt = $conn->prepare($query);
$stmt->execute();
$document_types_result = $stmt->get_result();
$document_types = [];

if ($document_types_result && $document_types_result->num_rows > 0) {
    while ($row = $document_types_result->fetch_assoc()) {
        $document_types[] = $row;
    }
}
$stmt->close();

// Get user's generated documents
$user_id = $_SESSION['user_id'];
$query = "SELECT gd.*, dt.name as document_type_name, 
          tmpl.name as template_name, CONCAT(creator.first_name, ' ', creator.last_name) as created_by_name
          FROM generated_documents gd
          JOIN document_types dt ON gd.document_type_id = dt.id
          JOIN document_templates tmpl ON gd.template_id = tmpl.id
          JOIN users creator ON gd.created_by = creator.id
          WHERE gd.client_id = ?
          ORDER BY gd.generated_date DESC";
$stmt = $conn->prepare($query);
$stmt->bind_param('i', $user_id);
$stmt->execute();
$generated_docs_result = $stmt->get_result();
$generated_documents = [];

if ($generated_docs_result && $generated_docs_result->num_rows > 0) {
    while ($row = $generated_docs_result->fetch_assoc()) {
        $generated_documents[] = $row;
    }
}
$stmt->close();

// Handle success messages
if (isset($_GET['success'])) {
    switch ($_GET['success']) {
        case 1:
            $success_message = "Document downloaded successfully";
            break;
        case 2:
            $success_message = "Document request sent successfully";
            break;
    }
}
?>

<div class="content">
    <div class="header-container">
        <div>
            <h1>My Documents</h1>
            <p>Access and manage your documents</p>
        </div>
        <button type="button" class="btn primary-btn" id="requestDocumentBtn">
            <i class="fas fa-plus"></i> Request Document
        </button>
    </div>
    
    <?php if (isset($error_message)): ?>
        <div class="alert alert-danger"><?php echo $error_message; ?></div>
    <?php endif; ?>
    
    <?php if (isset($success_message)): ?>
        <div class="alert alert-success"><?php echo $success_message; ?></div>
    <?php endif; ?>
    
    <!-- Tab Navigation -->
    <div class="tabs-container">
        <div class="tabs">
            <button class="tab-btn active" data-tab="my-documents">My Documents</button>
            <button class="tab-btn" data-tab="document-types">Document Types</button>
        </div>
        
        <!-- My Documents Tab -->
        <div class="tab-content active" id="my-documents-tab">
            <div class="tab-header">
                <h2>My Documents</h2>
            </div>
            
            <div class="tab-body">
                <?php if (empty($generated_documents)): ?>
                    <div class="empty-state">
                        <i class="fas fa-file-alt"></i>
                        <p>You don't have any documents yet. Request a document or wait for your consultant to generate one for you.</p>
                    </div>
                <?php else: ?>
                    <table class="data-table">
                        <thead>
                            <tr>
                                <th>Document Name</th>
                                <th>Document Type</th>
                                <th>Generated By</th>
                                <th>Generated Date</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($generated_documents as $document): ?>
                                <tr>
                                    <td><?php echo htmlspecialchars($document['name']); ?></td>
                                    <td><?php echo htmlspecialchars($document['document_type_name']); ?></td>
                                    <td><?php echo htmlspecialchars($document['created_by_name']); ?></td>
                                    <td><?php echo date('M d, Y H:i', strtotime($document['generated_date'])); ?></td>
                                    <td class="actions-cell">
                                        <a href="<?php echo htmlspecialchars($document['file_path']); ?>" class="btn-action btn-view" title="View Document" target="_blank">
                                            <i class="fas fa-eye"></i>
                                        </a>
                                        <a href="download_document.php?id=<?php echo $document['id']; ?>" class="btn-action btn-download" title="Download">
                                            <i class="fas fa-download"></i>
                                        </a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                <?php endif; ?>
            </div>
        </div>
        
        <!-- Document Types Tab -->
        <div class="tab-content" id="document-types-tab">
            <div class="tab-header">
                <h2>Available Document Types</h2>
            </div>
            
            <div class="tab-body">
                <?php if (empty($document_types)): ?>
                    <div class="empty-state">
                        <i class="fas fa-list-alt"></i>
                        <p>No document types available yet.</p>
                    </div>
                <?php else: ?>
                    <div class="category-container">
                        <?php 
                        $current_category = '';
                        foreach ($document_types as $type):
                            if ($type['category_name'] != $current_category):
                                if ($current_category != ''):
                                    echo '</ul></div>';
                                endif;
                                $current_category = $type['category_name'];
                        ?>
                            <div class="category-card">
                                <h3><?php echo htmlspecialchars($current_category); ?></h3>
                                <ul class="document-type-list">
                        <?php endif; ?>
                                    <li>
                                        <div class="document-type">
                                            <span class="document-type-name"><?php echo htmlspecialchars($type['name']); ?></span>
                                            <button type="button" class="btn-sm request-btn" onclick="requestSpecificDocument(<?php echo $type['id']; ?>, '<?php echo addslashes($type['name']); ?>')">
                                                Request
                                            </button>
                                        </div>
                                        <?php if (!empty($type['description'])): ?>
                                            <p class="document-type-description"><?php echo htmlspecialchars($type['description']); ?></p>
                                        <?php endif; ?>
                                    </li>
                        <?php endforeach; ?>
                                </ul>
                            </div>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>

<!-- Request Document Modal -->
<div class="modal" id="requestDocumentModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title">Request Document</h3>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <form action="request_document.php" method="POST" id="requestDocumentForm">
                    <div class="form-group">
                        <label for="document_type_id">Document Type*</label>
                        <select name="document_type_id" id="document_type_id" class="form-control" required>
                            <option value="">Select Document Type</option>
                            <?php foreach ($document_types as $type): ?>
                                <option value="<?php echo $type['id']; ?>"><?php echo htmlspecialchars($type['name']); ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="notes">Additional Notes</label>
                        <textarea name="notes" id="notes" class="form-control" rows="4" placeholder="Any specific requirements or information about your document request"></textarea>
                    </div>
                    <input type="hidden" name="user_id" value="<?php echo $user_id; ?>">
                    <div class="form-buttons">
                        <button type="button" class="btn cancel-btn" data-dismiss="modal">Cancel</button>
                        <button type="submit" name="request_document" class="btn submit-btn">Submit Request</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<style>
:root {
    --primary-color: #042167;
    --secondary-color: #858796;
    --success-color: #1cc88a;
    --danger-color: #e74a3b;
    --warning-color: #f6c23e;
    --light-color: #f8f9fc;
    --dark-color: #5a5c69;
    --border-color: #e3e6f0;
}

.content {
    padding: 20px;
}

.header-container {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 20px;
}

.header-container h1 {
    margin: 0;
    color: var(--primary-color);
    font-size: 1.8rem;
}

.header-container p {
    margin: 5px 0 0;
    color: var(--secondary-color);
}

.primary-btn {
    background-color: var(--primary-color);
    color: white;
    border: none;
    padding: 10px 20px;
    border-radius: 4px;
    font-weight: 500;
    cursor: pointer;
    display: flex;
    align-items: center;
    gap: 8px;
}

.primary-btn:hover {
    background-color: #031c56;
}

.tabs-container {
    background-color: white;
    border-radius: 5px;
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.05);
    overflow: hidden;
}

.tabs {
    display: flex;
    border-bottom: 1px solid var(--border-color);
}

.tab-btn {
    padding: 12px 20px;
    background: none;
    border: none;
    cursor: pointer;
    color: var(--secondary-color);
    font-weight: 500;
    position: relative;
}

.tab-btn:hover {
    color: var(--primary-color);
}

.tab-btn.active {
    color: var(--primary-color);
}

.tab-btn.active::after {
    content: '';
    position: absolute;
    bottom: -1px;
    left: 0;
    width: 100%;
    height: 3px;
    background-color: var(--primary-color);
}

.tab-content {
    display: none;
    padding: 20px;
}

.tab-content.active {
    display: block;
}

.tab-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 20px;
}

.tab-header h2 {
    margin: 0;
    color: var(--primary-color);
    font-size: 1.4rem;
}

.data-table {
    width: 100%;
    border-collapse: collapse;
}

.data-table th {
    background-color: var(--light-color);
    color: var(--primary-color);
    font-weight: 600;
    text-align: left;
    padding: 12px 15px;
    border-bottom: 1px solid var(--border-color);
}

.data-table td {
    padding: 12px 15px;
    border-bottom: 1px solid var(--border-color);
    color: var(--dark-color);
}

.data-table tbody tr:hover {
    background-color: rgba(4, 33, 103, 0.03);
}

.data-table tbody tr:last-child td {
    border-bottom: none;
}

.actions-cell {
    display: flex;
    gap: 8px;
    flex-wrap: wrap;
}

.btn-action {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 32px;
    height: 32px;
    border-radius: 4px;
    font-size: 14px;
    border: none;
    cursor: pointer;
    text-decoration: none;
    color: white;
    transition: background-color 0.2s;
}

.btn-view {
    background-color: var(--primary-color);
}

.btn-view:hover {
    background-color: #031c56;
}

.btn-download {
    background-color: var(--success-color);
}

.btn-download:hover {
    background-color: #19b67f;
}

.empty-state {
    text-align: center;
    padding: 50px 20px;
    color: var(--secondary-color);
}

.empty-state i {
    font-size: 48px;
    margin-bottom: 15px;
    opacity: 0.5;
}

.alert {
    padding: 12px 15px;
    border-radius: 4px;
    margin-bottom: 20px;
}

.alert-danger {
    background-color: rgba(231, 74, 59, 0.1);
    color: var(--danger-color);
    border: 1px solid rgba(231, 74, 59, 0.2);
}

.alert-success {
    background-color: rgba(28, 200, 138, 0.1);
    color: var(--success-color);
    border: 1px solid rgba(28, 200, 138, 0.2);
}

/* Modal Styles */
.modal {
    display: none;
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: rgba(0, 0, 0, 0.5);
    z-index: 1000;
    overflow: auto;
}

.modal-dialog {
    margin: 80px auto;
    max-width: 500px;
}

.modal-content {
    background-color: white;
    border-radius: 5px;
    box-shadow: 0 5px 15px rgba(0, 0, 0, 0.2);
}

.modal-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 15px 20px;
    border-bottom: 1px solid var(--border-color);
}

.modal-title {
    margin: 0;
    color: var(--primary-color);
    font-size: 1.4rem;
}

.close {
    background: none;
    border: none;
    font-size: 24px;
    cursor: pointer;
    color: var(--secondary-color);
}

.modal-body {
    padding: 20px;
}

.form-group {
    margin-bottom: 15px;
}

.form-group label {
    display: block;
    margin-bottom: 5px;
    font-weight: 500;
    color: var(--dark-color);
}

.form-control {
    width: 100%;
    padding: 10px;
    border: 1px solid var(--border-color);
    border-radius: 4px;
    font-size: 14px;
}

.form-control:focus {
    outline: none;
    border-color: var(--primary-color);
    box-shadow: 0 0 0 2px rgba(4, 33, 103, 0.1);
}

.form-buttons {
    display: flex;
    justify-content: flex-end;
    gap: 10px;
    margin-top: 20px;
}

.cancel-btn {
    background-color: white;
    color: var(--secondary-color);
    border: 1px solid var(--border-color);
    padding: 10px 20px;
    border-radius: 4px;
    cursor: pointer;
}

.submit-btn {
    background-color: var(--primary-color);
    color: white;
    border: none;
    padding: 10px 20px;
    border-radius: 4px;
    cursor: pointer;
}

.submit-btn:hover {
    background-color: #031c56;
}

/* Document Types Styles */
.category-container {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
    gap: 20px;
}

.category-card {
    background-color: var(--light-color);
    border-radius: 5px;
    padding: 20px;
    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.05);
}

.category-card h3 {
    color: var(--primary-color);
    font-size: 1.2rem;
    margin-top: 0;
    margin-bottom: 15px;
    border-bottom: 1px solid var(--border-color);
    padding-bottom: 10px;
}

.document-type-list {
    list-style: none;
    padding: 0;
    margin: 0;
}

.document-type-list li {
    margin-bottom: 15px;
    padding-bottom: 15px;
    border-bottom: 1px solid var(--border-color);
}

.document-type-list li:last-child {
    margin-bottom: 0;
    padding-bottom: 0;
    border-bottom: none;
}

.document-type {
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.document-type-name {
    font-weight: 500;
    color: var(--dark-color);
}

.document-type-description {
    margin-top: 5px;
    color: var(--secondary-color);
    font-size: 0.9rem;
}

.btn-sm {
    padding: 5px 10px;
    font-size: 12px;
    border-radius: 3px;
}

.request-btn {
    background-color: var(--primary-color);
    color: white;
    border: none;
    cursor: pointer;
}

.request-btn:hover {
    background-color: #031c56;
}

@media (max-width: 768px) {
    .header-container {
        flex-direction: column;
        align-items: flex-start;
        gap: 15px;
    }
    
    .tabs {
        overflow-x: auto;
    }
    
    .data-table {
        display: block;
        overflow-x: auto;
    }
    
    .modal-dialog {
        margin: 60px 15px;
    }
    
    .category-container {
        grid-template-columns: 1fr;
    }
}
</style>

<script>
// Tab functionality
document.querySelectorAll('.tab-btn').forEach(function(tab) {
    tab.addEventListener('click', function() {
        // Remove active class from all tabs
        document.querySelectorAll('.tab-btn').forEach(function(t) {
            t.classList.remove('active');
        });
        
        // Add active class to clicked tab
        this.classList.add('active');
        
        // Hide all tab content
        document.querySelectorAll('.tab-content').forEach(function(content) {
            content.classList.remove('active');
        });
        
        // Show corresponding tab content
        const tabId = this.getAttribute('data-tab');
        document.getElementById(tabId + '-tab').classList.add('active');
    });
});

// Modal functionality
function openModal(modalId) {
    document.getElementById(modalId).style.display = 'block';
}

function closeModal(modalId) {
    document.getElementById(modalId).style.display = 'none';
}

// Close modals when close button is clicked
document.querySelectorAll('[data-dismiss="modal"]').forEach(function(element) {
    element.addEventListener('click', function() {
        const modal = this.closest('.modal');
        if (modal) {
            modal.style.display = 'none';
        }
    });
});

// Close modal when clicking outside of it
window.addEventListener('click', function(event) {
    document.querySelectorAll('.modal').forEach(function(modal) {
        if (event.target === modal) {
            modal.style.display = 'none';
        }
    });
});

// Open request document modal
document.getElementById('requestDocumentBtn').addEventListener('click', function() {
    // Reset form
    document.getElementById('requestDocumentForm').reset();
    openModal('requestDocumentModal');
});

// Function to request a specific document type
function requestSpecificDocument(documentTypeId, documentTypeName) {
    document.getElementById('document_type_id').value = documentTypeId;
    openModal('requestDocumentModal');
}
</script>

<?php
// End output buffering and send content to browser
ob_end_flush();
?>

<?php require_once 'includes/footer.php'; ?>
